# Generated by Django 2.1 on 2018-10-06 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='登记药品编号')),
                ('drug_name', models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='药品名称')),
                ('mnemonic_code', models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='助记码')),
                ('manufacturer', models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='生产厂家')),
                ('specification', models.CharField(blank=True, default=' ', max_length=20, null=True, verbose_name='规格')),
                ('unit', models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='单位')),
                ('purchase_quantity', models.IntegerField(default=0, verbose_name='进货数量')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='进货日期')),
                ('serial_number', models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='产品批号')),
                ('validity_period', models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='有效期')),
                ('purchase_price', models.FloatField(default=0, verbose_name='进货价')),
                ('retail_price', models.FloatField(default=0, verbose_name='零售价')),
                ('wholesale_price', models.FloatField(default=0, verbose_name='批发价')),
                ('stock_num', models.IntegerField(default=0, verbose_name='库存')),
                ('property_classification', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='药品性质分类')),
                ('function_classification', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='药品功能分类')),
            ],
            options={
                'verbose_name': '药品',
                'verbose_name_plural': '所有药品信息',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='处方编号')),
                ('patient_name', models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='患者姓名')),
                ('patient_gender', models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='患者性别')),
                ('patient_age', models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='患者年龄')),
                ('illness_description', models.CharField(blank=True, default=' ', max_length=300, null=True, verbose_name='病症描述')),
                ('treatment_cost', models.FloatField(default=0, verbose_name='治疗费')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('doctor_name', models.CharField(blank=True, default='刘佃津', max_length=40, null=True, verbose_name='主治医生姓名')),
            ],
            options={
                'verbose_name': '门诊处方',
                'verbose_name_plural': '所有处方单',
            },
        ),
    ]
