# Generated by Django 2.1 on 2018-10-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyClinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='药方编号')),
                ('sale_amount', models.FloatField(default=0, verbose_name='治疗费')),
            ],
            options={
                'verbose_name': '处方开药',
                'verbose_name_plural': '所有处方开药记录',
            },
        ),
        migrations.AlterField(
            model_name='drug',
            name='purchase_quantity',
            field=models.FloatField(default=0, verbose_name='进货数量'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='stock_num',
            field=models.FloatField(default=0, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='unit',
            field=models.CharField(blank=True, choices=[('盒', '盒'), ('瓶', '瓶'), ('支', '支'), ('袋', '袋'), ('包', '包'), ('箱', '箱')], default='盒', max_length=40, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='illness_description',
            field=models.TextField(blank=True, default=' ', max_length=300, null=True, verbose_name='病症描述'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_age',
            field=models.IntegerField(default=1, verbose_name='患者年龄'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default=' ', max_length=10, null=True, verbose_name='患者性别'),
        ),
        migrations.AddField(
            model_name='medication',
            name='medicine_drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_drug', to='MyClinic.Drug', verbose_name='药品'),
        ),
        migrations.AddField(
            model_name='medication',
            name='medicine_prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_prescription', to='MyClinic.Prescription', verbose_name='处方'),
        ),
    ]
