# Generated by Django 2.1 on 2018-10-06 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClinic', '0002_auto_20181006_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='purchase_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='进货价'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='retail_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='零售价'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='stock_num',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='wholesale_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='批发价'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='sale_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='售货数量'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='患者年龄'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='treatment_cost',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='治疗费'),
        ),
    ]
