# Generated by Django 2.1 on 2018-10-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClinic', '0004_medication_sale_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient_gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='患者性别'),
        ),
    ]
